---
- hosts: jmeter

  tasks:
  - name: install java
    yum:
      name: java-1.8.0-openjdk
      state: present

  - name: Extract jmeter.zip
    unarchive:
      src: http://apache.stu.edu.tw/jmeter/binaries/apache-jmeter-5.4.zip
      dest: /opt/
      remote_src: True

  - name: Copiando alertscripts para o servidor
    copy:
      src: /root/cidadania_loop_100x10.jmx
      dest: /tmp/cidadania_loop_100x10.jmx

  - name: Ensure virtualenv is sourced from the .bashrc
    blockinfile:
      dest: "{{ ansible_env.HOME }}/.bashrc"
      block: |
          export JMETER_HOME=/opt/apache-jmeter-5.4/
          export PATH=$JMETER_HOME/bin:$PATH
      marker: '# {mark} ANSIBLE MANAGED BLOCK - virtualenv'
      insertbefore: BOF
      create: yes 
